mysql-server-8.0  mysql-server/root_password_again string root
mysql-server-8.0  mysql-server/root_password string root
mysql-server-8.0  mysql-server-8.0/installation_freeze_mode_active  note
mysql-server-8.0  mysql-server-8.0/postrm_remove_databases  boolean false
mysql-server-8.0  mysql-server-8.0/start_on_boot  boolean true
mysql-server-8.0  mysql-server-8.0/nis_warning  note