apiVersion: dp.wso2.com/v1alpha2
kind: API
metadata:
  name: springboot-helloworld-api
spec:
  apiName: SpringBoot Helloworld API
  apiType: REST
  apiVersion: 1.0.0
  basePath: /spring/1.0.0
  organization: default
  production:
  - routeRefs:
    - prod-http-route-springboot-helloworld
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: prod-http-route-springboot-helloworld
  namespace: default
spec:
  hostnames:
    - spring.gw.wso2.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: wso2-apk-default
      sectionName: httpslistener
  rules:
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: springboot-helloworld-backend
    matches:
    - method: GET
      path:
        type: RegularExpression
        value: /hello
---
apiVersion: dp.wso2.com/v1alpha1
kind: Backend
metadata:
  name: springboot-helloworld-backend
  namespace: default
spec:
  basePath: /
  protocol: http
  services:
  - host: spring-helloworld-service.default.svc
    port: 8080